# Generated by Django 5.1.2 on 2024-10-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dashboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
