# Generated by Django 5.1.2 on 2024-12-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboard_activated_dashboard_activation_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='activation_url',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='in_use',
            field=models.IntegerField(default=0),
        ),
    ]
