# Generated by Django 5.1.2 on 2024-10-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing',
            field=models.CharField(editable=False, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(editable=False, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(editable=False, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(editable=False, max_length=254, null=True),
        ),
    ]
