# Generated by Django 5.1.2 on 2024-10-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_billing_order_email_order_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_details',
            field=models.JSONField(null=True),
        ),
    ]
