# Generated by Django 5.1.2 on 2024-10-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_order_billing_order_billing_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='before migration', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_details',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
