# Generated by Django 5.1.2 on 2024-10-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_stripe_pid_alter_order_billing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(max_length=32),
        ),
    ]
