# Generated by Django 5.1.2 on 2024-10-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
