# Generated by Django 5.1.2 on 2024-11-28 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_billing_details'),
        ('reviews', '0006_remove_review_order_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
        ),
    ]
