# Generated by Django 5.1.2 on 2024-12-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_remove_orderlineitem_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
