# Generated by Django 5.1.2 on 2024-12-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_discount_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='max_discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
