# Generated by Django 5.1.2 on 2024-12-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_alter_orderlineitem_lineitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
