# Generated by Django 5.1.2 on 2024-10-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_content_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
