# Generated by Django 5.1.2 on 2024-10-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='store_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
