# Generated by Django 5.1.2 on 2024-12-01 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_remove_orderlineitem_review'),
        ('reviews', '0007_remove_review_product_review_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkout.orderlineitem'),
        ),
    ]
