# Generated by Django 5.1.2 on 2024-10-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
