# Generated by Django 5.1.2 on 2024-10-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_tag_alter_category_options_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='support_page',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(default='', max_length=10),
        ),
    ]
