# Generated by Django 5.1.2 on 2024-10-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_support_page_alter_brand_brand_alter_tag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='friendly_tag',
            field=models.CharField(default='', max_length=16),
        ),
    ]
