# Generated by Django 5.1.2 on 2024-11-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_reviews_product_rating_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
