# Generated by Django 5.1.2 on 2024-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
